config/routes.rb
Rickr::Application.routes.draw do
  
  get "api_tester/something"

  get "home/index"
  
  get "users/activate_twitter"
  
  get "users/twitter_callback"
  
  get "users/user_timeline"

  post "home/login", :as => 'login'

  get "home/logout"

  match '/photos/user/:id' => 'photos#show_photos_of_user', :as => 'user_photos'
  
  match '/albums/user/:id' => 'albums#show_albums_of_user', :as => 'user_albums'
  
  match '/photos/album/:id' => 'photos#show_photos_of_album', :as => 'album_photos'
  
  resources :albums

  resources :photos

  resources :users
  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos, :dependent => :destroy
  has_many :albums, :dependent => :destroy
  
  attr_accessible :admin, :first_name, :last_name, :password, :username, :email, :password_confirmation, :password_digest, :twitter_user
  
  has_secure_password
  
  validates_presence_of :first_name, :last_name, :username
  
  validates :username, :format => {:with => /[a-zA-Z][a-zA-Z0-9]*/}
  
  validates_uniqueness_of :username
  
  validates_confirmation_of :password, :message => "ya po, escribe bien la password!"
  
  def complete_name
    first_name + ' ' + last_name
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def user_timeline
    @access_token = OAuth::AccessToken.new(UsersController.consumer, current_user.twitter_token, current_user.twitter_secret)
    @response = UsersController.consumer.request(:get, "/1.1/statuses/user_timeline.json", @access_token, { :scheme => :query_string })
    @tweets = JSON::load(@response.body)
  end


  def activate_twitter
    @request_token = UsersController.consumer.get_request_token(:oauth_callback => "http://rickr.com:3000/users/twitter_callback")
    session[:request_token] = @request_token.token
    session[:request_token_secret] = @request_token.secret
    
    redirect_to @request_token.authorize_url
  end
  
  def twitter_callback
    @request_token = OAuth::RequestToken.new(UsersController.consumer, session[:request_token], session[:request_token_secret])
    @access_token = @request_token.get_access_token
    @response = UsersController.consumer.request(:get, '/1.1/account/verify_credentials.json', @access_token, { :scheme => :query_string })
    case @response
    when Net::HTTPSuccess
      user_info = JSON.parse(@response.body)
      unless user_info['screen_name']
        flash[:notice] = "Authentication failed"
        redirect_to :action => :index
        return
      end
      
      current_user.twitter_user = user_info['screen_name']
      current_user.twitter_token = @access_token.token
      current_user.twitter_secret = @access_token.secret
      current_user.save!
      flash[:notice] = "Twitter activated!"
      redirect_to(current_user)
        
    else
      flash[:notice] = "Authentication failed"
      redirect_to :action => :index
      return
    end
  end
  
  def self.consumer
    OAuth::Consumer.new("1dUnFX5lQYT8CIR5QYAfA", "DQZeP7uyPwXVTdBeoB4VyUFiY4AGILrAYpOgE0Ed7k", { :site=>"https://api.twitter.com" })    
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.xml { render xml: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    current_user
  end
  

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html {
          redirect_to @user, notice: 'User was successfully created.'
        }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :twitter_user %><br />
    <%= f.text_field :twitter_user %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Username</th>
    <th>Password</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
		<th></th>
		<th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.admin %></td>
		<td><%= link_to 'Photos', user_photos_path(user.id), :remote => true, 'data-type' => :html, 'data-update-element' => 'ainsert_here' %></td>
		<td><%= link_to 'Albums', user_albums_path(user.id) %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<div id="insert_here"></div>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.admin %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/user_timeline.html.erb
<h1>Timeline</h1>

<ul>
  <% @tweets.each do |tweet| %>
  <li><%= tweet['text'] %></li>

  <% end %>
</ul>