config/routes.rb
Rickr::Application.routes.draw do
  
  get "api_tester/something"

  get "home/index"
  
  get "users/activate_twitter"
  
  get "users/twitter_callback"
  
  get "users/user_timeline"

  post "home/login", :as => 'login'

  get "home/logout"

  match '/photos/user/:id' => 'photos#show_photos_of_user', :as => 'user_photos'
  
  match '/albums/user/:id' => 'albums#show_albums_of_user', :as => 'user_albums'
  
  match '/photos/album/:id' => 'photos#show_photos_of_album', :as => 'album_photos'
  
  resources :albums

  resources :photos

  resources :users
  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def login
    if u = User.find_by_username(params[:user][:username]).try(:authenticate, params[:user][:password])
      session[:user_id] = u.id
      flash[:notice] = "Bienvenido!, #{u.first_name}"
    else
      flash[:notice] = "Datos de ingreso incorrectos"
    end
    
    redirect_to :action => :index
  end

  def logout
    reset_session
    flash[:notice] = "Te deslogueaste, vuelve pronto! Si no..."
    redirect_to :action => :index
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if flash[:notice] %>
	<p class="notice"><%= flash[:notice] %></p>
<% end %>

<div id="example_images">
	<%= image_tag 'placeholder.png' %>
</div>
<div id="login_form">
	<h1>Bienvenido a <span class="rickr"><span>Rick</span>r</span>!</h1>

	<h2>Ingresa con tu nombre de usuario y contraseña</h2>

	<%= form_for 'user', :url => login_path do |f| %>
		<div class="field">
			<%= f.label 'username' %>
			<%= f.text_field 'username', :placeholder => 'ej. raulmt' %>
		</div>
		<div class="field">
			<%= f.label 'password' %>
			<%= f.password_field 'password' %>
		</div>
		<%= f.submit 'Login' %>
	<% end %>
</div>
<div class="clear"></div>
<div id="steps">
  <div id="step1">
    Paso 1 
  </div><div id="step2">
    Paso 2
  </div><div id="step3">
    Paso 3
  </div>
</div>

app/views/home/login.html.erb
<h1>Home#login</h1>
<p>Find me in app/views/home/login.html.erb</p>

app/views/home/logout.html.erb
<h1>Home#logout</h1>
<p>Find me in app/views/home/logout.html.erb</p>