config/routes.rb
Rickr::Application.routes.draw do
  
  get "api_tester/something"

  get "home/index"
  
  get "users/activate_twitter"
  
  get "users/twitter_callback"
  
  get "users/user_timeline"

  post "home/login", :as => 'login'

  get "home/logout"

  match '/photos/user/:id' => 'photos#show_photos_of_user', :as => 'user_photos'
  
  match '/albums/user/:id' => 'albums#show_albums_of_user', :as => 'user_albums'
  
  match '/photos/album/:id' => 'photos#show_photos_of_album', :as => 'album_photos'
  
  resources :albums

  resources :photos

  resources :users
  

  root :to => 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos, :through => :albums_photos
  has_many :albums_photos
  attr_accessible :description, :name, :user, :photos, :user_id
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def show_albums_of_user
    @albums = Album.find_all_by_user_id(params[:id])
    render :index
  end

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select :user_id, User.all, :id, :complete_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.description %></td>
    <td><%= link_to album.user.complete_name, album.user %></td>
    <td><%= link_to 'Photos', album_photos_path(album.id) %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>

<p>
  <b>User:</b>
  <%= link_to @album.user.complete_name, @album.user %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>