config/routes.rb
Rickr::Application.routes.draw do
  
  get "api_tester/something"

  get "home/index"
  
  get "users/activate_twitter"
  
  get "users/twitter_callback"
  
  get "users/user_timeline"

  post "home/login", :as => 'login'

  get "home/logout"

  match '/photos/user/:id' => 'photos#show_photos_of_user', :as => 'user_photos'
  
  match '/albums/user/:id' => 'albums#show_albums_of_user', :as => 'user_albums'
  
  match '/photos/album/:id' => 'photos#show_photos_of_album', :as => 'album_photos'
  
  resources :albums

  resources :photos

  resources :users
  

  root :to => 'home#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :albums, :through => :albums_photos
  has_many :albums_photos
  attr_accessible :description, :name, :path, :user, :user_id, :albums_photos_attributes
  
  accepts_nested_attributes_for :albums_photos, :allow_destroy => true, :reject_if => :all_blank
  
  def self.process_file(attrs)
    uploaded_file = attrs[:path]
    if uploaded_file
      File.open(Rails.root.join('public/assets/uploads', attrs[:path].original_filename), 'wb') do |file|
        file.write(uploaded_file.read)
      end
      attrs[:path] = uploaded_file.original_filename
    end
  end
  
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  layout 'clean_layout', :only => [:index]

  def show_photos_of_user
    @photos = Photo.where(:user_id => params[:id]).paginate(:page => params[:page], :per_page => 3)
    # para demorar mas el request ajax
    sleep 3
    respond_to do |format|
      format.html {
        if request.xhr?
          render :index, :layout => false
        else
          render :index
        end
      }
      format.js {
        @greeting = "Un saludo desde el controlador"
      }
    end
    
  end
  
  def show_photos_of_album
    @photos = Photo.joins(:albums_photos).where('albums_photos.album_id = ?', 1)
    render :index
  end
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.paginate(:page => params[:page], :per_page => 3)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new
    @photo.albums_photos.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
    @photo.albums_photos.build
  end

  # POST /photos
  # POST /photos.json
  def create
    Photo.process_file(params[:photo])
    @photo = Photo.new(params[:photo])
    
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])
    Photo.process_file(params[:photo])
    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.file_field :path %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select :user_id, User.all, :id, :complete_name %>
  </div>
	<div class="field">
		<%= label_tag 'Álbumes vinculados' %><br />
		<%= f.fields_for :albums_photos do |ap| %>
			<%= ap.label :album_id %>
			<%= ap.collection_select :album_id, Album.all, :id, :name, :include_blank => true %>
			<% if ap.object.album_id %>
				<%= ap.label '_destroy', 'Eliminar' %>
				<%= ap.check_box '_destroy' %>
			<% end %>
			<br />
		<% end %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<% content_for :header do  %>
  <h1>Fotos</h1>
<% end %>


<h1>Listado de fotos</h1>

<%= will_paginate @photos %>

<table>
  <tr>
    <th>Path</th>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
		<td><%= image_tag "uploads/#{photo.path}" %></td>
    <td><%= photo.name %></td>
    <td><%= photo.description %></td>
    <td><%= link_to photo.user.complete_name, photo.user %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @photos %>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @photo.path %>
</p>

<p>
  <b>Name:</b>
  <%= @photo.name %>
</p>

<p>
  <b>Description:</b>
  <%= @photo.description %>
</p>

<p>
  <b>User:</b>
  <%= link_to @photo.user.complete_name, @photo.user %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/photos/show_photos_of_user.js.erb
alert('<%= @greeting %>');

var elem = $('<div style="display: none;">Hola!</div>');
$(document.body).before(elem);
elem.show();